# Generated by Django 3.2.7 on 2021-10-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UVAClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_text', models.CharField(max_length=200)),
                ('studentyr_text', models.CharField(max_length=200)),
                ('classname_text', models.CharField(max_length=200)),
                ('classtime_text', models.CharField(max_length=200)),
                ('classprof_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Deepthought',
        ),
    ]
