# Generated by Django 3.2.8 on 2021-12-05 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
