# Generated by Django 3.2.7 on 2021-10-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211022_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uvaclass',
            old_name='classprof_text',
            new_name='classinst_text',
        ),
    ]
