# Generated by Django 3.2.8 on 2021-12-02 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_class',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='document_profile', to='main_app.class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='document_class', to='main_app.profile'),
            preserve_default=False,
        ),
    ]
