# Generated by Django 3.2.7 on 2021-11-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='computing_id',
            field=models.CharField(default='jyl3xf', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
