# Generated by Django 3.2.7 on 2021-11-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211104_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='computing_id',
            field=models.CharField(default='NULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
