# Generated by Django 3.2.8 on 2021-11-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211107_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='description',
        ),
    ]
