# Generated by Django 3.2.7 on 2021-11-04 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211104_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
