# Generated by Django 3.2.8 on 2021-11-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_title_document_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='title',
        ),
    ]
