# Generated by Django 3.2.7 on 2021-11-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='main_app.Class'),
        ),
        migrations.DeleteModel(
            name='UVAClass',
        ),
    ]
