# Generated by Django 3.2.7 on 2021-11-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20211104_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(related_name='profiles', to='main_app.Class'),
        ),
    ]
