# Generated by Django 3.2.7 on 2021-11-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_profile_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='department',
            new_name='day',
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
