# Generated by Django 3.2.7 on 2021-11-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20211104_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=30)),
                ('description', models.CharField(default='NULL', max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('class_name', models.CharField(default='NULL', max_length=30)),
                ('release_date', models.CharField(default='NULL', max_length=30)),
                ('due_date', models.CharField(default='NULL', max_length=30)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main_app.profile')),
            ],
        ),
    ]
