# Generated by Django 3.2.7 on 2021-11-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='NULL', max_length=30, primary_key=True, serialize=False),
        ),
    ]
