# Generated by Django 3.2.7 on 2021-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20211111_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='NULL', max_length=30),
        ),
    ]
