# Generated by Django 3.2.7 on 2021-11-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20211111_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main_app.profile'),
        ),
    ]
