# Generated by Django 3.2.7 on 2021-11-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_alter_assignment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
